name = "SDDESolarDynamo"
uuid = "9ae0b958-2da9-468f-b51c-a334fbbe8c62"
authors = ["Lorenzo Calandra Buonaura, Lucrezia Rossi & Andrea Turci"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
